name: Send a telegram message when new Youtube videos update 
on:
  youtube:
    channel_id:
      - UCMUnInmOkrWN4gof9KlhNmQ
      - UCseUQK4kC3x2x543nHtGpzw
jobs:
  telegram:
    name: send to telegram when youtube uploader upload new video
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: -683038354
          token: 6434634052:AAFVb2iLjZBi8ZlpjK3eZFsjollSTVCagZI
          message: |
            *${{on.youtube.outputs.title}}*
            
            ${{on.youtube.outputs.description}} ${{on.youtube.outputs.link}}
          format: markdown
